# Generated by Django 3.0.3 on 2020-03-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200303_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=6),
        ),
    ]
