# Generated by Django 3.0.3 on 2020-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200303_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(max_length=6),
        ),
    ]
