# Generated by Django 3.0.3 on 2020-03-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200304_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(choices=[('male', 'Male'), ('f', 'Female')], default='female', max_length=6),
        ),
    ]
