# Generated by Django 3.0.3 on 2020-03-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_annotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='annotator_id',
            new_name='annotator',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
