# Generated by Django 3.0.3 on 2020-03-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200305_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='terms',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='reponse',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Autre')], default='1', max_length=5),
        ),
    ]
