# Generated by Django 3.0.3 on 2020-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200306_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='reponse',
            field=models.CharField(choices=[('1', 'Oui'), ('0', 'Non'), ('2', 'Autre')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='terms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
