# Generated by Django 3.0.3 on 2020-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200306_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='terms',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
